"""make course code unique per department

Revision ID: cacd54703258
Revises: 4289094b5b61
Create Date: 2026-01-01 21:08:44.651576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cacd54703258'
down_revision: Union[str, Sequence[str], None] = '4289094b5b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    # ### end Alembic commands ###
